### ISSUE TITLE
Romanian translation proposal

### ISSUE THREAD

**Issue by budmc29** [ruby/www.ruby-lang.org#1523]
Hello all, my name is Mugur (Bud) and I am a happy Ruby developer.

I would like to open this proposal to create a **Romanian (ro)** translation for the website.

Currently I am alone, but I hope that in the next few weeks/months a few people could join to help maintaining this translation, and if not I am active enough to maintain it myself.

I understand that there is a lot of work to do, and that maintaining the translation is a continuous process, and that's fine for me.
Also I can provide new translations for when there will be a need, quick enough.

Let me know what are your thoughts on this.

**Comment by stomar** [comment]
Great to hear from you. We do welcome new translations (and there have been some - `ru` and `vi`- in the last couple of years). Yet due to past experiences I'm not inclined to do any preparatory setup and coordination work until it seems clear that there is a **team of motivated and reliable contributors**.

See #699 (milestones) to get an impression of the work involved initially with the static content, and www.ruby-lang.org/admin/translation-status to get an impression of the on-going work related to news post translations; see also the discussion in #670.

**Comment by budmc29** [comment]
@stomar what should I do to get started?

**Comment by budmc29** [comment]
Looking for anyone that can help me start this task.
Please post here if you are interested in helping with a Romanian translation.
