### ISSUE TITLE
Ruby 3 release announcement lacks Ruby version

### ISSUE THREAD

**Issue by Quintus** [ruby/www.ruby-lang.org#2584]
I mean, like, it says on https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/ this:

> We are pleased to announce the release of Ruby .

I get that Ruby 3 makes all shiny and new, but is it really equivalent to the first release of Ruby, ever?

Seriously: During translation I found that there's a macro at that point that is supposed to be evaluated, but it appearently does not evaluate. I've used "3" directly in the German translation, but I'd like to make you aware the problem exists in the English original already.

**Comment by stomar** [comment]
The `release.version` variable is assigned later, after the first paragraph, hence the Ruby version was missing in the first paragraph of the rendered page.

Assigning the variable before the first paragraph, at the very beginning of the post, is no option, because this would break the news excerpts on the main page and news archive pages.
