### ISSUE TITLE
www.ruby-lang.org needs a Privacy Policy page

### ISSUE THREAD

**Issue by lanrebr** [ruby/www.ruby-lang.org#3134]
We find that our organization is refusing permission to install and use Ruby only because we cannot locate a privacy policy page that describes what what data is being collected by the web site, how it’s being collected, how it is stored, for how long it is stored , what it is being used for and how it is being shared.

Can we please add a Privacy Policy page nothing that the web site does not collect any information from any user?

**Comment by hsbt** [comment]
@lanrebr Is https://www.php.net/privacy.php enough to your requirement? We are not company, foundation or NPO. It's difficult to provide detailed privacy policy.

**Comment by lanrebr** [comment]
@hsbt thank you for looking into this. Yes I think something like the php privacy page would be a good starting point as it indicates that ruby will not need anything else than the email address and it would not share it with anyone.

**Comment by hsbt** [comment]
Thanks. I'll consider that.

**Comment by rubyFeedback** [comment]
Agreed. I think it may suffice to simply document what will happen with the data; and what data is stored. This should cover most of it; for the rest I think it would be fine to add a new issue at the ruby bug tracker, and to ask people to add their concern, along with a time limit for the discussion, say 1-2 months, so that it can then be closed and made official (and perhaps also have it for an upcoming ruby developer meeting to ask them about it).

**Comment by lanrebr** [comment]
Thank you do very much!!!!

**Comment by lanrebr** [comment]
Just a small note to let you know that there is a spell typo in new policy page. It reads Ascknowledgements instead of Acknowledgements.
Thank you

**Comment by lanrebr** [comment]
Thank you
